export const DEMO_PASSWORD = 'demo1234';

/** Fixed seed clock so expires_at stays the same when seed runs again. 09:00 Asia/Bangkok. */
export const SEED_AT_ISO = '2026-09-22T02:00:00.000Z';

export const CO2E_PER_KG = 2.5;

export const DEPOT = {
  name: 'จุดรวบรวมวิสาหกิจชุมชน',
  lat: 13.65,
  lng: 100.62,
} as const;

/** Plan fallback. The prototype screen uses 34°C / 78% when weather fails. */
export const PLAN_WEATHER_FALLBACK = { tempC: 32, humidity: 75 } as const;

export const PROTOTYPE_WEATHER_FALLBACK = { tempC: 34, humidity: 78 } as const;

export const RIPENESS_LABELS = ['ดิบ', 'เริ่มสุก', 'สุกพอดี', 'สุกมาก', 'ใกล้งอม'] as const;

export const crops = [
  {
    key: 'mango',
    nameTh: 'มะม่วง',
    nameEn: 'Mango',
    categoryId: 1,
    baseShelfDays: 5,
    marketPricePerKg: 40,
    parcelAllowed: true,
    storageTipTh: 'สุกบนชั้นวางจนหอมแล้วค่อยแช่เย็น ถ้าหั่นแล้วเก็บตู้เย็นไม่เกิน 2–3 วัน ให้ผึ่งให้แห้ง',
    storageTipEn: 'Ripen at room temperature; refrigerate cut fruit 2–3 days and keep dry',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh:
      'ผิวเรียบหรือเป็นลายจุดเล็ก ๆ ตามพันธุ์, สีเปลือกเปลี่ยนตามความสุก, ขั้วติดแน่น, ไม่มีน้ำเยิ้ม',
    defectExamplesTh: 'รอยช้ำนิ่มยุบ, แผลแตก, ราขาว/ดำ, จุดดำที่ยุบลึก, เนื้อฉ่ำน้ำผิดปกติ, กลิ่นหมัก',
  },
  {
    key: 'banana',
    nameTh: 'กล้วยน้ำว้า',
    nameEn: 'Namwa banana',
    categoryId: 1,
    baseShelfDays: 4,
    marketPricePerKg: 25,
    parcelAllowed: false,
    storageTipTh: 'สุกที่อุณหภูมิห้อง แล้วแช่เย็นเพื่อยืดอายุเปลือกได้อีกหลายวัน แยกจากผักที่ไวต่อเอทิลีน',
    storageTipEn: 'Ripen at room temperature; refrigerate to slow peel browning; keep from ethylene-sensitive produce',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh:
      'จุดน้ำตาลเล็ก ๆ บนเปลือกเมื่อสุก, ปลายขั้วและปลายผลสีดำ, รอยเส้นตามแนวยาวของเปลือก',
    defectExamplesTh: 'รอยช้ำนิ่มยุบ, แผลแตก, รา, จุดดำที่ยุบลึกลงเนื้อ, เปลือกฉีก',
  },
  {
    key: 'tomato',
    nameTh: 'มะเขือเทศ',
    nameEn: 'Tomato',
    categoryId: 3,
    baseShelfDays: 6,
    marketPricePerKg: 30,
    parcelAllowed: false,
    storageTipTh: 'วางขั้วขึ้นที่อุณหภูมิห้องจนสุก แช่เย็นเฉพาะเมื่อสุกเต็มที่หรือหั่นแล้ว ใช้ภายในไม่กี่วัน',
    storageTipEn: 'Stem-up at room temperature until ripe; refrigerate only if fully ripe or cut',
    fridgeOk: true,
    fridgeExtraDays: 4,
    normalFeaturesTh: 'ผิวตึงตามความสุก, ขั้วเขียวหรือน้ำตาลอ่อน, จุดสีตามพันธุ์, ไม่มีน้ำไหล',
    defectExamplesTh: 'รอยช้ำนิ่ม, แผลแตก, รา, จุดดำยุบ, เน่าที่ขั้ว',
  },
  {
    key: 'morning-glory',
    nameTh: 'ผักบุ้ง',
    nameEn: 'Morning glory',
    categoryId: 2,
    baseShelfDays: 2,
    marketPricePerKg: 20,
    parcelAllowed: false,
    storageTipTh: 'ความชื้นสูง ใช้ภายใน 1–2 วัน ล้างก่อนใช้ ทิ้งใบที่เหลืองหรือเละ',
    storageTipEn: 'High humidity; use within 1–2 days; wash before use; discard yellow or slimy leaves',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh: 'ใบเขียวสด อาจมีจุดน้ำเล็กน้อยหลังเก็บ, ลำต้นกรอบ ไม่เหลืองทั้งต้น',
    defectExamplesTh: 'ใบเหลืองไหม้, เน่าเละ, รา, ลำต้นเละยุบ, กลิ่นเหม็น',
  },
  {
    key: 'lime',
    nameTh: 'มะนาว',
    nameEn: 'Lime',
    categoryId: 1,
    baseShelfDays: 14,
    marketPricePerKg: 35,
    parcelAllowed: true,
    storageTipTh: 'ที่แห้งเย็น หรือตู้เย็นช่องผักเพื่อยืดอายุ หลีกเลี่ยงความชื้นส่วนเกิน',
    storageTipEn: 'Keep cool and dry or refrigerate in the crisper; avoid excess moisture',
    fridgeOk: true,
    fridgeExtraDays: 14,
    normalFeaturesTh: 'ผิวขรุขระตามพันธุ์, จุดน้ำมันบนเปลือก, สีเขียวถึงเหลืองอ่อนตามความสุก',
    defectExamplesTh: 'รอยช้ำยุบ, แผลแตก, ราขาว, จุดดำเน่า, เปลือกแห้งเหี่ยวผิดปกติ',
  },
  // --- additional crops added for 6.3 ---
  {
    key: 'durian',
    nameTh: 'ทุเรียน',
    nameEn: 'Durian',
    categoryId: 1,
    baseShelfDays: 3,
    marketPricePerKg: 150,
    parcelAllowed: false,
    storageTipTh: 'เก็บในที่เย็นและอากาศถ่ายเทดี ห่อด้วยพลาสติกให้แน่นก่อนแช่เย็น ใช้ภายใน 1–2 วันหลังเปิด',
    storageTipEn: 'Keep in a cool, well-ventilated spot; wrap tightly before refrigerating; use within 1–2 days once opened',
    fridgeOk: true,
    fridgeExtraDays: 1,
    normalFeaturesTh: 'เปลือกหนามแน่น กลิ่นหอมชัดเมื่อสุก ขั้วเขียวหรือน้ำตาลอ่อน',
    defectExamplesTh: 'เปลือกแตกร้าวและเนื้อสีน้ำตาล เนื้อเละเป็นน้ำ ราบนเปลือก กลิ่นเปรี้ยวผิดปกติ',
  },
  {
    key: 'pomelo',
    nameTh: 'ส้มโอ',
    nameEn: 'Pomelo',
    categoryId: 1,
    baseShelfDays: 14,
    marketPricePerKg: 35,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่อุณหภูมิห้องที่เย็นและแห้ง หรือแช่เย็นเพื่อยืดอายุ ไม่ต้องใส่ถุง',
    storageTipEn: 'Store at cool room temperature or refrigerate; no need to bag',
    fridgeOk: true,
    fridgeExtraDays: 7,
    normalFeaturesTh: 'เปลือกเหลืองหรือเขียวตามพันธุ์ แน่น ไม่มีรอยบุบ ขั้วติดแน่น',
    defectExamplesTh: 'รอยบุบยุบ รา เปลือกนิ่มผิดปกติ กลิ่นหมัก',
  },
  {
    key: 'longan',
    nameTh: 'ลำไย',
    nameEn: 'Longan',
    categoryId: 1,
    baseShelfDays: 5,
    marketPricePerKg: 50,
    parcelAllowed: true,
    storageTipTh: 'แช่เย็นในถุงระบายอากาศ ใช้ภายใน 5–7 วัน ล้างก่อนรับประทาน',
    storageTipEn: 'Refrigerate in a ventilated bag; use within 5–7 days; wash before eating',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'เปลือกสีน้ำตาลทองสม่ำเสมอ เนื้อขาวใสเต่งตึง รสหวาน',
    defectExamplesTh: 'เปลือกดำหรือขึ้นรา เนื้อเหลืองคล้ำ รสเปรี้ยวผิดปกติ ก้านเน่า',
  },
  {
    key: 'rambutan',
    nameTh: 'เงาะ',
    nameEn: 'Rambutan',
    categoryId: 1,
    baseShelfDays: 4,
    marketPricePerKg: 40,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นในถุงพลาสติกหลวม ๆ ใช้ภายใน 3–5 วัน ไม่ควรวางกองซ้อนหนัก',
    storageTipEn: 'Refrigerate loosely in a plastic bag; use within 3–5 days; avoid stacking heavily',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh: 'ขนสีแดงหรือเหลืองแน่นยืดหยุ่น ขั้วเขียวสด เปลือกไม่เหี่ยว',
    defectExamplesTh: 'ขนดำ เปลือกเหี่ยวหดแห้ง รา กลิ่นหมัก เนื้อเละ',
  },
  {
    key: 'guava',
    nameTh: 'ฝรั่ง',
    nameEn: 'Guava',
    categoryId: 1,
    baseShelfDays: 5,
    marketPricePerKg: 25,
    parcelAllowed: true,
    storageTipTh: 'วางที่อุณหภูมิห้องจนสุก แล้วแช่เย็น ใช้ภายใน 3–5 วัน',
    storageTipEn: 'Ripen at room temperature then refrigerate; use within 3–5 days',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'ผิวเขียวหรือเหลืองอ่อนตามพันธุ์ กลิ่นหอมอ่อน ๆ เนื้อแน่น',
    defectExamplesTh: 'รอยช้ำยุบ แผลแตก รา เนื้อเละ กลิ่นหมัก',
  },
  {
    key: 'pineapple',
    nameTh: 'สับปะรด',
    nameEn: 'Pineapple',
    categoryId: 1,
    baseShelfDays: 5,
    marketPricePerKg: 20,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่อุณหภูมิห้อง 2–3 วัน หลังตัดแช่เย็นในภาชนะปิด ใช้ภายใน 3–5 วัน',
    storageTipEn: 'Store at room temperature 2–3 days; once cut, refrigerate in a sealed container and use within 3–5 days',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'ตาแน่น เปลือกสีทองหรือเขียวปนทอง กลิ่นหวานหอม ก้านแน่น',
    defectExamplesTh: 'ตาเน่าดำ เปลือกเหลืองคล้ำผิดปกติ รา กลิ่นหมัก น้ำไหลที่รอยตัด',
  },
  {
    key: 'custard-apple',
    nameTh: 'น้อยหน่า',
    nameEn: 'Custard apple',
    categoryId: 1,
    baseShelfDays: 3,
    marketPricePerKg: 45,
    parcelAllowed: false,
    storageTipTh: 'สุกที่อุณหภูมิห้อง แล้วแช่เย็นทันทีและใช้ภายใน 1–2 วัน ไม่ควรกดหรือกองซ้อน',
    storageTipEn: 'Ripen at room temperature; refrigerate immediately when ripe and use within 1–2 days; handle gently',
    fridgeOk: true,
    fridgeExtraDays: 1,
    normalFeaturesTh: 'ผิวสีเขียวอมเทาตามพันธุ์ ตาผิวแยกออกเล็กน้อยเมื่อสุก เนื้อนวลขาว',
    defectExamplesTh: 'ผิวดำเน่า เนื้อเละหรือคล้ำผิดปกติ รา กลิ่นหมักหรือเปรี้ยว',
  },
  {
    key: 'chinese-kale',
    nameTh: 'คะน้า',
    nameEn: 'Chinese kale',
    categoryId: 2,
    baseShelfDays: 3,
    marketPricePerKg: 30,
    parcelAllowed: false,
    storageTipTh: 'ห่อด้วยผ้าชื้นหรือกระดาษชำระ แช่เย็น ใช้ภายใน 3–4 วัน ล้างก่อนใช้',
    storageTipEn: 'Wrap in a damp cloth or paper towel; refrigerate; use within 3–4 days; wash before use',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh: 'ใบเขียวเข้ม แน่น เส้นใบชัด ลำต้นสีเขียวอ่อนหรือขาว',
    defectExamplesTh: 'ใบเหลืองไหม้ เนื้อเละ รา ลำต้นเหี่ยว กลิ่นเหม็น',
  },
  {
    key: 'napa-cabbage',
    nameTh: 'ผักกาดขาว',
    nameEn: 'Napa cabbage',
    categoryId: 2,
    baseShelfDays: 7,
    marketPricePerKg: 25,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นห่อพลาสติกหลวม ๆ ใช้ภายใน 7–10 วัน ตัดรอยช้ำออกก่อนใช้',
    storageTipEn: 'Refrigerate loosely wrapped; use within 7–10 days; trim any bruised leaves before use',
    fridgeOk: true,
    fridgeExtraDays: 4,
    normalFeaturesTh: 'ใบขาวเหลืองอ่อนหรือเขียวอ่อน แน่นแน่ว ไม่มีรอยช้ำ',
    defectExamplesTh: 'ใบเหลืองคล้ำ รา เนื้อเหลว กลิ่นเหม็น',
  },
  {
    key: 'cilantro',
    nameTh: 'ผักชี',
    nameEn: 'Coriander (cilantro)',
    categoryId: 2,
    baseShelfDays: 3,
    marketPricePerKg: 60,
    parcelAllowed: false,
    storageTipTh: 'ใส่ขวดน้ำเล็กน้อยแล้วแช่เย็น หรือห่อด้วยกระดาษชื้น ใช้ภายใน 3–5 วัน',
    storageTipEn: 'Stand in a small amount of water and refrigerate, or wrap in damp paper; use within 3–5 days',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh: 'ใบเขียวสดกลิ่นหอมชัดเจน ลำต้นเขียวหรือขาว ไม่เหลือง',
    defectExamplesTh: 'ใบเหลืองหรือดำ เนื้อเละ รา กลิ่นเหม็นหรือหายไป',
  },
  {
    key: 'green-onion',
    nameTh: 'ต้นหอม',
    nameEn: 'Green onion',
    categoryId: 2,
    baseShelfDays: 4,
    marketPricePerKg: 50,
    parcelAllowed: false,
    storageTipTh: 'ห่อด้วยกระดาษชำระชื้นแล้วใส่ถุงแช่เย็น ใช้ภายใน 4–5 วัน',
    storageTipEn: 'Wrap in damp paper towel, place in a bag and refrigerate; use within 4–5 days',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'ส่วนใบเขียวสด ส่วนขาวแน่นสะอาด กลิ่นหอมฉุน',
    defectExamplesTh: 'ใบเหลือง เนื้อเละ รา กลิ่นเน่าเหม็น',
  },
  {
    key: 'cucumber',
    nameTh: 'แตงกวา',
    nameEn: 'Cucumber',
    categoryId: 3,
    baseShelfDays: 5,
    marketPricePerKg: 20,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็น ไม่ตัดก่อนเก็บ ใช้ภายใน 5–7 วัน',
    storageTipEn: 'Refrigerate whole (do not cut before storing); use within 5–7 days',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'ผิวเขียวเต่งตึง หนามเล็ก ๆ ยังมีอยู่ ไม่มีรอยยุบ',
    defectExamplesTh: 'รอยยุบนิ่ม ผิวเหลืองคล้ำ รา เนื้อเละหรือขมผิดปกติ',
  },
  {
    key: 'chili',
    nameTh: 'พริก',
    nameEn: 'Chili',
    categoryId: 3,
    baseShelfDays: 7,
    marketPricePerKg: 60,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นในถุงกระดาษหรือภาชนะที่ระบายอากาศได้ ใช้ภายใน 1–2 สัปดาห์',
    storageTipEn: 'Refrigerate in a paper bag or ventilated container; use within 1–2 weeks',
    fridgeOk: true,
    fridgeExtraDays: 5,
    normalFeaturesTh: 'ผิวเขียวหรือแดงแน่นเงา ขั้วเขียวสด ไม่มีรอยแตกหรือยุบ',
    defectExamplesTh: 'รอยยุบนิ่ม แผลแตก ราขาวหรือดำ ขั้วเหี่ยว เนื้อเละ',
  },
  {
    key: 'thai-eggplant',
    nameTh: 'มะเขือยาว',
    nameEn: 'Thai eggplant',
    categoryId: 3,
    baseShelfDays: 5,
    marketPricePerKg: 30,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นในถุงพลาสติก ใช้ภายใน 5–7 วัน ตัดส่วนที่ช้ำออกก่อนใช้',
    storageTipEn: 'Refrigerate in a plastic bag; use within 5–7 days; trim bruised areas before use',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'ผิวม่วงหรือขาวเงาแน่น ขั้วเขียวสด ไม่มีรอยยุบ',
    defectExamplesTh: 'รอยช้ำยุบ ผิวสีน้ำตาลดำ รา เนื้อฟองเละผิดปกติ',
  },
  {
    key: 'cabbage',
    nameTh: 'กะหล่ำปลี',
    nameEn: 'Cabbage',
    categoryId: 2,
    baseShelfDays: 10,
    marketPricePerKg: 20,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็น ไม่ตัดก่อนเก็บ ใช้ภายใน 2 สัปดาห์',
    storageTipEn: 'Refrigerate whole; use within 2 weeks',
    fridgeOk: true,
    fridgeExtraDays: 7,
    normalFeaturesTh: 'ใบชั้นนอกเขียวสด แน่นหนัก ก้านแน่น',
    defectExamplesTh: 'ใบดำเน่า ใบเหลืองคล้ำ รา กลิ่นเหม็น',
  },
  {
    key: 'corn',
    nameTh: 'ข้าวโพด',
    nameEn: 'Corn',
    categoryId: 3,
    baseShelfDays: 2,
    marketPricePerKg: 15,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นทันที ไม่ปอกเปลือก ใช้ภายใน 1–2 วันเพื่อรสชาติที่ดีที่สุด',
    storageTipEn: 'Refrigerate immediately with husks on; use within 1–2 days for best flavour',
    fridgeOk: true,
    fridgeExtraDays: 1,
    normalFeaturesTh: 'เปลือกเขียวชื้น เส้นไหมสีเหลืองสด เมล็ดอวบเต็มสม่ำเสมอ',
    defectExamplesTh: 'เมล็ดยุบแห้ง ราบนเปลือก แมลงเจาะ เมล็ดสีน้ำตาลเน่า',
  },
  {
    key: 'long-bean',
    nameTh: 'ถั่วฝักยาว',
    nameEn: 'Long bean',
    categoryId: 3,
    baseShelfDays: 3,
    marketPricePerKg: 30,
    parcelAllowed: false,
    storageTipTh: 'ห่อด้วยผ้าชื้นแช่เย็น ใช้ภายใน 3–4 วัน อย่าล้างก่อนเก็บ',
    storageTipEn: 'Wrap in a damp cloth and refrigerate; use within 3–4 days; do not wash before storing',
    fridgeOk: true,
    fridgeExtraDays: 2,
    normalFeaturesTh: 'ฝักเขียวเต่งตึงสม่ำเสมอ ไม่มีรอยช้ำหรือจุดดำ',
    defectExamplesTh: 'ฝักเหลืองหรือเหี่ยว รอยช้ำนิ่ม รา จุดดำ',
  },
  {
    key: 'pumpkin',
    nameTh: 'ฟักทอง',
    nameEn: 'Pumpkin',
    categoryId: 3,
    baseShelfDays: 14,
    marketPricePerKg: 20,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่เย็นแห้งและอากาศถ่ายเทดี หลังตัดแช่เย็นในภาชนะปิด ใช้ภายใน 5 วัน',
    storageTipEn: 'Store in a cool, dry, ventilated spot; once cut, refrigerate in a sealed container and use within 5 days',
    fridgeOk: true,
    fridgeExtraDays: 7,
    normalFeaturesTh: 'ผิวแข็งเขียวหรือส้มตามพันธุ์ ขั้วแห้งกลมแน่น',
    defectExamplesTh: 'ผิวยุบเน่า รา จุดดำยุบลึก เนื้อเหลวผิดปกติ',
  },
  {
    key: 'lemongrass',
    nameTh: 'ตะไคร้',
    nameEn: 'Lemongrass',
    categoryId: 4,
    baseShelfDays: 7,
    marketPricePerKg: 40,
    parcelAllowed: false,
    storageTipTh: 'แช่เย็นในถุงพลาสติก ใช้ภายใน 1–2 สัปดาห์ หรือแช่แข็งได้นาน 3 เดือน',
    storageTipEn: 'Refrigerate in a plastic bag for 1–2 weeks, or freeze for up to 3 months',
    fridgeOk: true,
    fridgeExtraDays: 7,
    normalFeaturesTh: 'ก้านสีเขียวอ่อนหรือเหลืองนวล กลิ่นซิตรัสชัดเจน ไม่มีรอยเน่า',
    defectExamplesTh: 'ก้านดำเน่า กลิ่นหายหรือเหม็น รา เนื้อเละ',
  },
  {
    key: 'holy-basil',
    nameTh: 'ใบกะเพรา',
    nameEn: 'Holy basil',
    categoryId: 4,
    baseShelfDays: 3,
    marketPricePerKg: 60,
    parcelAllowed: false,
    storageTipTh: 'ห่อด้วยกระดาษชำระชื้นแช่เย็น ใช้ภายใน 2–3 วัน',
    storageTipEn: 'Wrap in damp paper towel and refrigerate; use within 2–3 days',
    fridgeOk: true,
    fridgeExtraDays: 1,
    normalFeaturesTh: 'ใบเขียวหรือม่วงสดกลิ่นหอมเฉพาะตัว ไม่เหลือง',
    defectExamplesTh: 'ใบเหลืองดำ เนื้อเละ รา กลิ่นเหม็น',
  },
  {
    key: 'ginger',
    nameTh: 'ขิง',
    nameEn: 'Ginger',
    categoryId: 4,
    baseShelfDays: 14,
    marketPricePerKg: 50,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่แห้งอุณหภูมิห้อง หรือแช่เย็น ใช้ภายใน 2–3 สัปดาห์',
    storageTipEn: 'Store dry at room temperature or refrigerate; use within 2–3 weeks',
    fridgeOk: true,
    fridgeExtraDays: 14,
    normalFeaturesTh: 'ผิวสีน้ำตาลอ่อนหรือทอง เต่งตึง เนื้อเหลืองอมเขียว กลิ่นฉุน',
    defectExamplesTh: 'รอยยุบเหี่ยว ราขาวดำ เนื้อเละ กลิ่นเปรี้ยวผิดปกติ',
  },
  {
    key: 'sweet-potato',
    nameTh: 'มันเทศ',
    nameEn: 'Sweet potato',
    categoryId: 5,
    baseShelfDays: 14,
    marketPricePerKg: 25,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 2–4 สัปดาห์',
    storageTipEn: 'Store in a cool, dry, ventilated spot; do not refrigerate; use within 2–4 weeks',
    fridgeOk: false,
    fridgeExtraDays: 0,
    normalFeaturesTh: 'ผิวสีม่วงหรือส้มตามพันธุ์ แน่น ไม่มีรอยช้ำหรือรา',
    defectExamplesTh: 'รอยช้ำยุบ รา เนื้อดำ กลิ่นเหม็น',
  },
  {
    key: 'shallot',
    nameTh: 'หอมแดง',
    nameEn: 'Shallot',
    categoryId: 5,
    baseShelfDays: 21,
    marketPricePerKg: 60,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 3–4 สัปดาห์',
    storageTipEn: 'Store in a cool, dry, ventilated spot; do not refrigerate; use within 3–4 weeks',
    fridgeOk: false,
    fridgeExtraDays: 0,
    normalFeaturesTh: 'เปลือกแห้งสีน้ำตาลแดง เนื้อแน่น ไม่งอก ไม่เหลือง',
    defectExamplesTh: 'งอกยาว เปลือกเน่าดำ รา เนื้อเละ',
  },
  {
    key: 'garlic',
    nameTh: 'กระเทียม',
    nameEn: 'Garlic',
    categoryId: 5,
    baseShelfDays: 21,
    marketPricePerKg: 80,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 3–4 สัปดาห์',
    storageTipEn: 'Store in a cool, dry, ventilated spot; do not refrigerate; use within 3–4 weeks',
    fridgeOk: false,
    fridgeExtraDays: 0,
    normalFeaturesTh: 'เปลือกขาวหรือม่วงแห้งแน่น กลีบแน่นไม่งอก ไม่มีรา',
    defectExamplesTh: 'งอกยาว เปลือกเน่าดำ รา เนื้อกลีบเละ กลิ่นเปรี้ยว',
  },
  {
    key: 'mangosteen',
    nameTh: 'มังคุด',
    nameEn: 'Mangosteen',
    categoryId: 1,
    baseShelfDays: 7,
    marketPricePerKg: 80,
    parcelAllowed: true,
    storageTipTh: 'เก็บที่เย็น 10–13°C ห่อด้วยกระดาษ ใช้ภายใน 1 สัปดาห์',
    storageTipEn: 'Store at 10–13°C wrapped in paper; use within 1 week',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'เปลือกสีม่วงเข้มแน่น กลีบสีเขียวสด ไม่มียางเหลืองไหล',
    defectExamplesTh: 'เปลือกแข็งแน่น ยางเหลืองไหล เนื้อดำน้ำตาล รา',
  },
  {
    key: 'lychee',
    nameTh: 'ลิ้นจี่',
    nameEn: 'Lychee',
    categoryId: 1,
    baseShelfDays: 5,
    marketPricePerKg: 70,
    parcelAllowed: true,
    storageTipTh: 'แช่เย็น 2–5°C ใส่ถุงผักสด ใช้ภายใน 3–5 วัน',
    storageTipEn: 'Refrigerate at 2–5°C in a produce bag; use within 3–5 days',
    fridgeOk: true,
    fridgeExtraDays: 3,
    normalFeaturesTh: 'เปลือกสีแดงอมชมพูสด เนื้อใสหวาน เมล็ดเล็ก',
    defectExamplesTh: 'เปลือกน้ำตาลดำ เนื้อเมือก กลิ่นหมัก',
  },
] as const;

export type CropKey = (typeof crops)[number]['key'];

export interface CropSeasonFactor {
  cropKey: CropKey;
  month: number; // 1-12
  factor: number; // < 1 = peak (cheap), > 1 = off-season (expensive), 1.0 = normal (not stored)
}

// Seasonal price factors based on OAE production calendar.
// Direction: peak harvest = high supply = prices DROP (factor < 1).
// Off-season = low supply = prices RISE (factor > 1).
// Only non-1.0 months are listed; missing months default to 1.0.
// Factor magnitudes are team estimates for demo purposes, not official OAE data.
export const cropSeasonFactors: CropSeasonFactor[] = [
  // มะม่วง — peak Mar-Jun (Eastern/Central Thailand)
  { cropKey: 'mango', month: 3, factor: 0.75 },
  { cropKey: 'mango', month: 4, factor: 0.70 },
  { cropKey: 'mango', month: 5, factor: 0.70 },
  { cropKey: 'mango', month: 6, factor: 0.80 },
  { cropKey: 'mango', month: 10, factor: 1.25 },
  { cropKey: 'mango', month: 11, factor: 1.30 },
  { cropKey: 'mango', month: 12, factor: 1.35 },
  { cropKey: 'mango', month: 1, factor: 1.35 },
  // ทุเรียน — peak Apr-Jun (Eastern Thailand); Oct = 1.0 (normal, not stored)
  { cropKey: 'durian', month: 3, factor: 0.85 },
  { cropKey: 'durian', month: 4, factor: 0.65 },
  { cropKey: 'durian', month: 5, factor: 0.60 },
  { cropKey: 'durian', month: 6, factor: 0.65 },
  { cropKey: 'durian', month: 7, factor: 0.85 },
  { cropKey: 'durian', month: 11, factor: 1.30 },
  { cropKey: 'durian', month: 12, factor: 1.40 },
  { cropKey: 'durian', month: 1, factor: 1.40 },
  { cropKey: 'durian', month: 2, factor: 1.30 },
  // ลำไย — peak Jul-Aug (Northern Thailand)
  { cropKey: 'longan', month: 6, factor: 0.85 },
  { cropKey: 'longan', month: 7, factor: 0.65 },
  { cropKey: 'longan', month: 8, factor: 0.65 },
  { cropKey: 'longan', month: 9, factor: 0.85 },
  { cropKey: 'longan', month: 1, factor: 1.35 },
  { cropKey: 'longan', month: 2, factor: 1.40 },
  { cropKey: 'longan', month: 3, factor: 1.35 },
  { cropKey: 'longan', month: 4, factor: 1.25 },
  { cropKey: 'longan', month: 5, factor: 1.15 },
  // เงาะ — peak May-Jul (Eastern Thailand)
  { cropKey: 'rambutan', month: 4, factor: 0.85 },
  { cropKey: 'rambutan', month: 5, factor: 0.70 },
  { cropKey: 'rambutan', month: 6, factor: 0.65 },
  { cropKey: 'rambutan', month: 7, factor: 0.70 },
  { cropKey: 'rambutan', month: 8, factor: 0.85 },
  { cropKey: 'rambutan', month: 11, factor: 1.25 },
  { cropKey: 'rambutan', month: 12, factor: 1.30 },
  { cropKey: 'rambutan', month: 1, factor: 1.35 },
  { cropKey: 'rambutan', month: 2, factor: 1.30 },
  { cropKey: 'rambutan', month: 3, factor: 1.25 },
  // ส้มโอ — peak Aug-Nov (Central Thailand); Oct = 0.75
  { cropKey: 'pomelo', month: 8, factor: 0.85 },
  { cropKey: 'pomelo', month: 9, factor: 0.70 },
  { cropKey: 'pomelo', month: 10, factor: 0.75 },
  { cropKey: 'pomelo', month: 11, factor: 0.75 },
  { cropKey: 'pomelo', month: 12, factor: 0.85 },
  { cropKey: 'pomelo', month: 3, factor: 1.30 },
  { cropKey: 'pomelo', month: 4, factor: 1.35 },
  { cropKey: 'pomelo', month: 5, factor: 1.30 },
  { cropKey: 'pomelo', month: 6, factor: 1.15 },
  // น้อยหน่า — peak Jul-Oct (Northern Thailand)
  { cropKey: 'custard-apple', month: 7, factor: 0.85 },
  { cropKey: 'custard-apple', month: 8, factor: 0.70 },
  { cropKey: 'custard-apple', month: 9, factor: 0.70 },
  { cropKey: 'custard-apple', month: 10, factor: 0.75 },
  { cropKey: 'custard-apple', month: 11, factor: 0.85 },
  { cropKey: 'custard-apple', month: 1, factor: 1.25 },
  { cropKey: 'custard-apple', month: 2, factor: 1.30 },
  { cropKey: 'custard-apple', month: 3, factor: 1.30 },
  { cropKey: 'custard-apple', month: 4, factor: 1.25 },
  // มังคุด — peak Apr-Jun (Eastern Thailand)
  { cropKey: 'mangosteen', month: 3, factor: 0.85 },
  { cropKey: 'mangosteen', month: 4, factor: 0.65 },
  { cropKey: 'mangosteen', month: 5, factor: 0.60 },
  { cropKey: 'mangosteen', month: 6, factor: 0.65 },
  { cropKey: 'mangosteen', month: 7, factor: 0.85 },
  { cropKey: 'mangosteen', month: 11, factor: 1.25 },
  { cropKey: 'mangosteen', month: 12, factor: 1.35 },
  { cropKey: 'mangosteen', month: 1, factor: 1.40 },
  { cropKey: 'mangosteen', month: 2, factor: 1.30 },
  // ลิ้นจี่ — peak Apr-Jun (Northern Thailand)
  { cropKey: 'lychee', month: 3, factor: 0.80 },
  { cropKey: 'lychee', month: 4, factor: 0.65 },
  { cropKey: 'lychee', month: 5, factor: 0.60 },
  { cropKey: 'lychee', month: 6, factor: 0.70 },
  { cropKey: 'lychee', month: 10, factor: 1.25 },
  { cropKey: 'lychee', month: 11, factor: 1.35 },
  { cropKey: 'lychee', month: 12, factor: 1.40 },
  { cropKey: 'lychee', month: 1, factor: 1.35 },
  { cropKey: 'lychee', month: 2, factor: 1.25 },
];

export const buyers = [
  { name: 'PaDaRed Vendor (รถพุ่มพวงป้าแดง)', buyerType: 'vendor', lat: 13.662, lng: 100.611, phone: '0800000011' },
  { name: 'Community Children Home (บ้านพักเด็กชุมชน)', buyerType: 'charity', lat: 13.641, lng: 100.634, phone: '0800000012' },
  { name: "Lung Chom Curry Shop (ร้านข้าวแกงลุงชม)", buyerType: 'shop', lat: 13.657, lng: 100.642, phone: '0800000013' },
] as const;

export const staff = [
  { role: 'driver', name: 'Demo Driver (คนขับตัวอย่าง)', phone: '0800000004' },
  { role: 'coordinator', name: 'admin', phone: '0800000005' },
] as const;

export const farmers = [
  {
    name: 'Somchai Farmer (ลุงสมชาย)',
    shopName: 'Somchai Farm (สวนลุงสมชาย)',
    phone: '0800000001',
    plotName: 'Somchai Plot (แปลงลุงสมชาย)',
    lat: 13.668,
    lng: 100.628,
    areaRai: 1,
    lot: {
      cropKey: 'mango' as const,
      weightKg: 80,
      grade: 'substandard' as const,
      ripeness: 3,
      hoursLeft: 20,
      allowDonation: true,
    },
  },
  {
    name: 'Bunmee Farmer (ป้าบุญมี)',
    shopName: 'Bunmee Farm (สวนป้าบุญมี)',
    phone: '0800000002',
    plotName: 'Bunmee Plot (แปลงป้าบุญมี)',
    lat: 13.645,
    lng: 100.605,
    areaRai: 1,
    lot: {
      cropKey: 'morning-glory' as const,
      weightKg: 25,
      grade: 'normal' as const,
      ripeness: 2,
      hoursLeft: 30,
      allowDonation: false,
    },
  },
  {
    name: 'Tom Farmer (พี่ต้อม)',
    shopName: 'Tom Farm (สวนพี่ต้อม)',
    phone: '0800000003',
    plotName: 'Tom Plot (แปลงพี่ต้อม)',
    lat: 13.635,
    lng: 100.622,
    areaRai: 1,
    lot: {
      cropKey: 'tomato' as const,
      weightKg: 60,
      grade: 'substandard' as const,
      ripeness: 3,
      hoursLeft: 70,
      allowDonation: true,
    },
  },
] as const;

/**
 * Expected shelf-life / price samples.
 * tempC + humidity are daytime (10:00–17:00) averages over the next 72h.
 * Price is the normal-grade urgent price when hoursLeft equals shelfHours.
 * Humidity above 85% shortens shelf-life by 10% (see DECISIONS.md).
 */
export const phase2Samples = [
  { cropKey: 'mango' as const, ripeness: 2, tempC: 34, humidity: 78, shelfHours: 61, priceNormal: 26 },
  { cropKey: 'mango' as const, ripeness: 3, tempC: 34, humidity: 78, shelfHours: 44 },
  { cropKey: 'mango' as const, ripeness: 2, tempC: 34, humidity: 90, shelfHours: 55 },
] as const;
