-- Agri-Rescue reference/lookup data seed.
--
-- The university DB was created from docs/database/schema.sql, which only
-- inserts a handful of sample rows -- it does not include the reference
-- catalog data that the app's migrations (server/src/db/migrations) and
-- seed script (server/src/db/seed.ts) populate on a dev install.
--
-- This file:
--   1. Clears ALL Agri-Rescue tables (children first) so the sample rows
--      from schema.sql are removed and there are no ID clashes or orphan
--      rows pointing at the old sample crops. It does NOT touch the other
--      project's tables sharing this database (categories, group_products,
--      products, product_stores, stock_movements, stores, inventory_users,
--      schema_migrations).
--   2. Re-inserts the reference/lookup data only (crop_categories, crops,
--      crop_season_factors, crop_reference_prices) as dumped from a local
--      dev install of agri_rescue. No user-generated data (users, plots,
--      harvest_lots, orders, notifications, etc.) is included.
--
-- Import via phpMyAdmin against the existing university schema (schema.sql
-- must already be loaded). Safe to re-run.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Clear existing Agri-Rescue rows (children before parents; FK checks are
--    off above so order is for hygiene, not correctness).
DELETE FROM support_attachments;
DELETE FROM support_messages;
DELETE FROM support_tickets;
DELETE FROM impact_logs;
DELETE FROM donation_infractions;
DELETE FROM donation_proofs;
DELETE FROM route_stops;
DELETE FROM payments;
DELETE FROM orders;
DELETE FROM batches;
DELETE FROM quality_assessments;
DELETE FROM lot_delete_logs;
DELETE FROM lot_edit_logs;
DELETE FROM lot_photos;
DELETE FROM harvest_lots;
DELETE FROM dit_mapping_suggestions;
DELETE FROM plots;
DELETE FROM shop_follows;
DELETE FROM shops;
DELETE FROM notifications;
DELETE FROM crop_reference_prices;
DELETE FROM crop_season_factors;
DELETE FROM crops;
DELETE FROM crop_categories;
DELETE FROM org_review_logs;
DELETE FROM org_application_docs;
DELETE FROM buyer_profiles;
DELETE FROM users;

ALTER TABLE crop_categories AUTO_INCREMENT = 1;
ALTER TABLE crops AUTO_INCREMENT = 1;
ALTER TABLE crop_season_factors AUTO_INCREMENT = 1;
ALTER TABLE crop_reference_prices AUTO_INCREMENT = 1;

-- 2. Reference data (data-only, dumped from local dev DB agri_rescue).

INSERT INTO `crop_categories` (`id`, `name_th`, `name_en`, `sort_order`, `default_shelf_days`, `parcel_allowed`, `default_normal_features_th`, `default_defect_examples_th`) VALUES (1,'ผลไม้','Fruit',1,5,1,'สีเปลือกสม่ำเสมอตามพันธุ์ ผิวไม่มีรอยยุบหรือน้ำไหล ขั้วติดแน่น','รอยช้ำยุบ แผลแตก รา จุดดำยุบลึก กลิ่นหมักหรือเน่า');
INSERT INTO `crop_categories` (`id`, `name_th`, `name_en`, `sort_order`, `default_shelf_days`, `parcel_allowed`, `default_normal_features_th`, `default_defect_examples_th`) VALUES (2,'ผักใบ','Leafy vegetables',2,2,0,'ใบเขียวสดเต่งตึง ลำต้นกรอบไม่เหลือง','ใบเหลืองไหม้ เน่าเละ รา ลำต้นเละ กลิ่นเหม็น');
INSERT INTO `crop_categories` (`id`, `name_th`, `name_en`, `sort_order`, `default_shelf_days`, `parcel_allowed`, `default_normal_features_th`, `default_defect_examples_th`) VALUES (3,'ผักผล','Fruit vegetables',3,5,0,'ผิวตึงสม่ำเสมอ ไม่มีรอยยุบหรือน้ำไหล ขั้วสดหรือสีเหลืองอ่อน','รอยช้ำนิ่ม แผลแตก รา จุดดำยุบ เน่าที่ขั้ว');
INSERT INTO `crop_categories` (`id`, `name_th`, `name_en`, `sort_order`, `default_shelf_days`, `parcel_allowed`, `default_normal_features_th`, `default_defect_examples_th`) VALUES (4,'สมุนไพร','Herbs',4,4,0,'ใบหรือต้นสดเขียว กลิ่นหอมเฉพาะตัว','เหลืองเหี่ยว เน่าเละ รา กลิ่นเหม็น');
INSERT INTO `crop_categories` (`id`, `name_th`, `name_en`, `sort_order`, `default_shelf_days`, `parcel_allowed`, `default_normal_features_th`, `default_defect_examples_th`) VALUES (5,'หัว/ราก','Roots & tubers',5,14,1,'ผิวแน่น ไม่มีรอยยุบหรือขึ้นราชัดเจน','รอยช้ำยุบ ราขาว เนื้อเละ กลิ่นเปรี้ยวผิดปกติ');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (1,'มะม่วง','Mango',1,5,45.00,'W14026','มะม่วงเขียวเสวย เบอร์ 0',NULL,NULL,'auto',NULL,'ผิวเรียบหรือเป็นลายจุดเล็ก ๆ ตามพันธุ์, สีเปลือกเปลี่ยนตามความสุก, ขั้วติดแน่น, ไม่มีน้ำเยิ้ม','รอยช้ำนิ่มยุบ, แผลแตก, ราขาว/ดำ, จุดดำที่ยุบลึก, เนื้อฉ่ำน้ำผิดปกติ, กลิ่นหมัก','สุกบนชั้นวางจนหอมแล้วค่อยแช่เย็น ถ้าหั่นแล้วเก็บตู้เย็นไม่เกิน 2–3 วัน ให้ผึ่งให้แห้ง','Ripen at room temperature; refrigerate cut fruit 2–3 days and keep dry',1,2,1,'approved',NULL,'2026-09-26 16:47:19');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (2,'กล้วยน้ำว้า','Namwa banana',1,4,25.00,'W14009','กล้วยน้ำว้า',NULL,NULL,'auto',NULL,'จุดน้ำตาลเล็ก ๆ บนเปลือกเมื่อสุก, ปลายขั้วและปลายผลสีดำ, รอยเส้นตามแนวยาวของเปลือก','รอยช้ำนิ่มยุบ, แผลแตก, รา, จุดดำที่ยุบลึกลงเนื้อ, เปลือกฉีก','สุกที่อุณหภูมิห้อง แล้วแช่เย็นเพื่อยืดอายุเปลือกได้อีกหลายวัน แยกจากผักที่ไวต่อเอทิลีน','Ripen at room temperature; refrigerate to slow peel browning; keep from ethylene-sensitive produce',1,3,0,'approved',NULL,'2026-09-26 16:47:19');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (3,'มะเขือเทศ','Tomato',3,6,25.00,'W13010','มะเขือเทศผลใหญ่',NULL,NULL,'auto',NULL,'ผิวตึงตามความสุก, ขั้วเขียวหรือน้ำตาลอ่อน, จุดสีตามพันธุ์, ไม่มีน้ำไหล','รอยช้ำนิ่ม, แผลแตก, รา, จุดดำยุบ, เน่าที่ขั้ว','วางขั้วขึ้นที่อุณหภูมิห้องจนสุก แช่เย็นเฉพาะเมื่อสุกเต็มที่หรือหั่นแล้ว ใช้ภายในไม่กี่วัน','Stem-up at room temperature until ripe; refrigerate only if fully ripe or cut',1,4,0,'approved',NULL,'2026-09-26 16:47:19');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (4,'ผักบุ้ง','Morning glory',2,2,28.00,'W13002','ผักบุ้งจีน',NULL,NULL,'auto',NULL,'ใบเขียวสด อาจมีจุดน้ำเล็กน้อยหลังเก็บ, ลำต้นกรอบ ไม่เหลืองทั้งต้น','ใบเหลืองไหม้, เน่าเละ, รา, ลำต้นเละยุบ, กลิ่นเหม็น','ความชื้นสูง ใช้ภายใน 1–2 วัน ล้างก่อนใช้ ทิ้งใบที่เหลืองหรือเละ','High humidity; use within 1–2 days; wash before use; discard yellow or slimy leaves',1,2,0,'approved',NULL,'2026-09-26 16:47:19');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (5,'มะนาว','Lime',1,14,35.00,'W13025','มะนาว เบอร์ 1-2',NULL,NULL,'auto',NULL,'ผิวขรุขระตามพันธุ์, จุดน้ำมันบนเปลือก, สีเขียวถึงเหลืองอ่อนตามความสุก','รอยช้ำยุบ, แผลแตก, ราขาว, จุดดำเน่า, เปลือกแห้งเหี่ยวผิดปกติ','ที่แห้งเย็น หรือตู้เย็นช่องผักเพื่อยืดอายุ หลีกเลี่ยงความชื้นส่วนเกิน','Keep cool and dry or refrigerate in the crisper; avoid excess moisture',1,14,1,'approved',NULL,'2026-09-26 16:47:19');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (6,'ทุเรียน','Durian',1,3,100.00,'W14020','ทุเรียนชะนี',NULL,NULL,'auto',NULL,'เปลือกหนามแน่น กลิ่นหอมชัดเมื่อสุก ขั้วเขียวหรือน้ำตาลอ่อน','เปลือกแตกร้าวและเนื้อสีน้ำตาล เนื้อเละเป็นน้ำ ราบนเปลือก กลิ่นเปรี้ยวผิดปกติ','เก็บในที่เย็นและอากาศถ่ายเทดี ห่อด้วยพลาสติกให้แน่นก่อนแช่เย็น ใช้ภายใน 1–2 วันหลังเปิด','Keep in a cool, well-ventilated spot; wrap tightly before refrigerating; use within 1–2 days once opened',1,1,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (7,'ส้มโอ','Pomelo',1,14,25.00,'W14005','ส้มโอ ขาวทองดี เล็ก',NULL,NULL,'auto',NULL,'เปลือกเหลืองหรือเขียวตามพันธุ์ แน่น ไม่มีรอยบุบ ขั้วติดแน่น','รอยบุบยุบ รา เปลือกนิ่มผิดปกติ กลิ่นหมัก','เก็บที่อุณหภูมิห้องที่เย็นและแห้ง หรือแช่เย็นเพื่อยืดอายุ ไม่ต้องใส่ถุง','Store at cool room temperature or refrigerate; no need to bag',1,7,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (8,'ลำไย','Longan',1,5,50.00,'W14032','ลำไย อีดอ',NULL,NULL,'auto',NULL,'เปลือกสีน้ำตาลทองสม่ำเสมอ เนื้อขาวใสเต่งตึง รสหวาน','เปลือกดำหรือขึ้นรา เนื้อเหลืองคล้ำ รสเปรี้ยวผิดปกติ ก้านเน่า','แช่เย็นในถุงระบายอากาศ ใช้ภายใน 5–7 วัน ล้างก่อนรับประทาน','Refrigerate in a ventilated bag; use within 5–7 days; wash before eating',1,3,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (9,'เงาะ','Rambutan',1,4,40.00,'W14019','เงาะโรงเรียน',NULL,NULL,'auto',NULL,'ขนสีแดงหรือเหลืองแน่นยืดหยุ่น ขั้วเขียวสด เปลือกไม่เหี่ยว','ขนดำ เปลือกเหี่ยวหดแห้ง รา กลิ่นหมัก เนื้อเละ','แช่เย็นในถุงพลาสติกหลวม ๆ ใช้ภายใน 3–5 วัน ไม่ควรวางกองซ้อนหนัก','Refrigerate loosely in a plastic bag; use within 3–5 days; avoid stacking heavily',1,2,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (10,'ฝรั่ง','Guava',1,5,15.00,'W14012','ฝรั่งกิมจู คละ',NULL,NULL,'auto',NULL,'ผิวเขียวหรือเหลืองอ่อนตามพันธุ์ กลิ่นหอมอ่อน ๆ เนื้อแน่น','รอยช้ำยุบ แผลแตก รา เนื้อเละ กลิ่นหมัก','วางที่อุณหภูมิห้องจนสุก แล้วแช่เย็น ใช้ภายใน 3–5 วัน','Ripen at room temperature then refrigerate; use within 3–5 days',1,3,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (11,'สับปะรด','Pineapple',1,5,15.00,'W14014','สับปะรด ศรีราชา เบอร์ 1',NULL,NULL,'auto',NULL,'ตาแน่น เปลือกสีทองหรือเขียวปนทอง กลิ่นหวานหอม ก้านแน่น','ตาเน่าดำ เปลือกเหลืองคล้ำผิดปกติ รา กลิ่นหมัก น้ำไหลที่รอยตัด','เก็บที่อุณหภูมิห้อง 2–3 วัน หลังตัดแช่เย็นในภาชนะปิด ใช้ภายใน 3–5 วัน','Store at room temperature 2–3 days; once cut, refrigerate in a sealed container and use within 3–5 days',1,3,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (12,'น้อยหน่า','Custard apple',1,3,45.00,'W14031','น้อยหน่า',NULL,NULL,'auto',NULL,'ผิวสีเขียวอมเทาตามพันธุ์ ตาผิวแยกออกเล็กน้อยเมื่อสุก เนื้อนวลขาว','ผิวดำเน่า เนื้อเละหรือคล้ำผิดปกติ รา กลิ่นหมักหรือเปรี้ยว','สุกที่อุณหภูมิห้อง แล้วแช่เย็นทันทีและใช้ภายใน 1–2 วัน ไม่ควรกดหรือกองซ้อน','Ripen at room temperature; refrigerate immediately when ripe and use within 1–2 days; handle gently',1,1,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (13,'คะน้า','Chinese kale',2,3,20.00,'W13001','ผักคะน้า',NULL,NULL,'auto',NULL,'ใบเขียวเข้ม แน่น เส้นใบชัด ลำต้นสีเขียวอ่อนหรือขาว','ใบเหลืองไหม้ เนื้อเละ รา ลำต้นเหี่ยว กลิ่นเหม็น','ห่อด้วยผ้าชื้นหรือกระดาษชำระ แช่เย็น ใช้ภายใน 3–4 วัน ล้างก่อนใช้','Wrap in a damp cloth or paper towel; refrigerate; use within 3–4 days; wash before use',1,2,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (14,'ผักกาดขาว','Napa cabbage',2,7,15.00,'W13005','ผักกาดขาว (ลุ้ย)',NULL,NULL,'auto',NULL,'ใบขาวเหลืองอ่อนหรือเขียวอ่อน แน่นแน่ว ไม่มีรอยช้ำ','ใบเหลืองคล้ำ รา เนื้อเหลว กลิ่นเหม็น','แช่เย็นห่อพลาสติกหลวม ๆ ใช้ภายใน 7–10 วัน ตัดรอยช้ำออกก่อนใช้','Refrigerate loosely wrapped; use within 7–10 days; trim any bruised leaves before use',1,4,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (15,'ผักชี','Coriander (cilantro)',2,3,80.00,'W13018','ผักชี',NULL,NULL,'auto',NULL,'ใบเขียวสดกลิ่นหอมชัดเจน ลำต้นเขียวหรือขาว ไม่เหลือง','ใบเหลืองหรือดำ เนื้อเละ รา กลิ่นเหม็นหรือหายไป','ใส่ขวดน้ำเล็กน้อยแล้วแช่เย็น หรือห่อด้วยกระดาษชื้น ใช้ภายใน 3–5 วัน','Stand in a small amount of water and refrigerate, or wrap in damp paper; use within 3–5 days',1,2,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (16,'ต้นหอม','Green onion',2,4,55.00,'W13019','ต้นหอม',NULL,NULL,'auto',NULL,'ส่วนใบเขียวสด ส่วนขาวแน่นสะอาด กลิ่นหอมฉุน','ใบเหลือง เนื้อเละ รา กลิ่นเน่าเหม็น','ห่อด้วยกระดาษชำระชื้นแล้วใส่ถุงแช่เย็น ใช้ภายใน 4–5 วัน','Wrap in damp paper towel, place in a bag and refrigerate; use within 4–5 days',1,3,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (17,'แตงกวา','Cucumber',3,5,20.00,'W13013','แตงกวา',NULL,NULL,'auto',NULL,'ผิวเขียวเต่งตึง หนามเล็ก ๆ ยังมีอยู่ ไม่มีรอยยุบ','รอยยุบนิ่ม ผิวเหลืองคล้ำ รา เนื้อเละหรือขมผิดปกติ','แช่เย็น ไม่ตัดก่อนเก็บ ใช้ภายใน 5–7 วัน','Refrigerate whole (do not cut before storing); use within 5–7 days',1,3,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (18,'พริก','Chili',3,7,40.00,'W13021','พริกขี้หนูจินดา (แดง)',NULL,NULL,'auto',NULL,'ผิวเขียวหรือแดงแน่นเงา ขั้วเขียวสด ไม่มีรอยแตกหรือยุบ','รอยยุบนิ่ม แผลแตก ราขาวหรือดำ ขั้วเหี่ยว เนื้อเละ','แช่เย็นในถุงกระดาษหรือภาชนะที่ระบายอากาศได้ ใช้ภายใน 1–2 สัปดาห์','Refrigerate in a paper bag or ventilated container; use within 1–2 weeks',1,5,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (19,'มะเขือยาว','Thai eggplant',3,5,20.00,NULL,NULL,NULL,NULL,NULL,NULL,'ผิวม่วงหรือขาวเงาแน่น ขั้วเขียวสด ไม่มีรอยยุบ','รอยช้ำยุบ ผิวสีน้ำตาลดำ รา เนื้อฟองเละผิดปกติ','แช่เย็นในถุงพลาสติก ใช้ภายใน 5–7 วัน ตัดส่วนที่ช้ำออกก่อนใช้','Refrigerate in a plastic bag; use within 5–7 days; trim bruised areas before use',1,3,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (20,'กะหล่ำปลี','Cabbage',2,10,12.00,'W13006','กะหล่ำปลี',NULL,NULL,'auto',NULL,'ใบชั้นนอกเขียวสด แน่นหนัก ก้านแน่น','ใบดำเน่า ใบเหลืองคล้ำ รา กลิ่นเหม็น','แช่เย็น ไม่ตัดก่อนเก็บ ใช้ภายใน 2 สัปดาห์','Refrigerate whole; use within 2 weeks',1,7,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (21,'ข้าวโพด','Corn',3,2,10.00,'W13017','ข้าวโพดฝักอ่อน',NULL,NULL,'auto',NULL,'เปลือกเขียวชื้น เส้นไหมสีเหลืองสด เมล็ดอวบเต็มสม่ำเสมอ','เมล็ดยุบแห้ง ราบนเปลือก แมลงเจาะ เมล็ดสีน้ำตาลเน่า','แช่เย็นทันที ไม่ปอกเปลือก ใช้ภายใน 1–2 วันเพื่อรสชาติที่ดีที่สุด','Refrigerate immediately with husks on; use within 1–2 days for best flavour',1,1,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (22,'ถั่วฝักยาว','Long bean',3,3,30.00,'W13012','ถั่วฝักยาว',NULL,NULL,'auto',NULL,'ฝักเขียวเต่งตึงสม่ำเสมอ ไม่มีรอยช้ำหรือจุดดำ','ฝักเหลืองหรือเหี่ยว รอยช้ำนิ่ม รา จุดดำ','ห่อด้วยผ้าชื้นแช่เย็น ใช้ภายใน 3–4 วัน อย่าล้างก่อนเก็บ','Wrap in a damp cloth and refrigerate; use within 3–4 days; do not wash before storing',1,2,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (23,'ฟักทอง','Pumpkin',3,14,13.00,NULL,NULL,NULL,NULL,NULL,NULL,'ผิวแข็งเขียวหรือส้มตามพันธุ์ ขั้วแห้งกลมแน่น','ผิวยุบเน่า รา จุดดำยุบลึก เนื้อเหลวผิดปกติ','เก็บที่เย็นแห้งและอากาศถ่ายเทดี หลังตัดแช่เย็นในภาชนะปิด ใช้ภายใน 5 วัน','Store in a cool, dry, ventilated spot; once cut, refrigerate in a sealed container and use within 5 days',1,7,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (24,'ตะไคร้','Lemongrass',4,7,10.00,NULL,NULL,NULL,NULL,NULL,NULL,'ก้านสีเขียวอ่อนหรือเหลืองนวล กลิ่นซิตรัสชัดเจน ไม่มีรอยเน่า','ก้านดำเน่า กลิ่นหายหรือเหม็น รา เนื้อเละ','แช่เย็นในถุงพลาสติก ใช้ภายใน 1–2 สัปดาห์ หรือแช่แข็งได้นาน 3 เดือน','Refrigerate in a plastic bag for 1–2 weeks, or freeze for up to 3 months',1,7,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (25,'ใบกะเพรา','Holy basil',4,3,30.00,NULL,NULL,NULL,NULL,NULL,NULL,'ใบเขียวหรือม่วงสดกลิ่นหอมเฉพาะตัว ไม่เหลือง','ใบเหลืองดำ เนื้อเละ รา กลิ่นเหม็น','ห่อด้วยกระดาษชำระชื้นแช่เย็น ใช้ภายใน 2–3 วัน','Wrap in damp paper towel and refrigerate; use within 2–3 days',1,1,0,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (26,'ขิง','Ginger',4,14,20.00,'W13028','ขิงแก่ คละ',NULL,NULL,'auto',NULL,'ผิวสีน้ำตาลอ่อนหรือทอง เต่งตึง เนื้อเหลืองอมเขียว กลิ่นฉุน','รอยยุบเหี่ยว ราขาวดำ เนื้อเละ กลิ่นเปรี้ยวผิดปกติ','เก็บที่แห้งอุณหภูมิห้อง หรือแช่เย็น ใช้ภายใน 2–3 สัปดาห์','Store dry at room temperature or refrigerate; use within 2–3 weeks',1,14,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (27,'มันเทศ','Sweet potato',5,14,25.00,NULL,NULL,NULL,NULL,NULL,NULL,'ผิวสีม่วงหรือส้มตามพันธุ์ แน่น ไม่มีรอยช้ำหรือรา','รอยช้ำยุบ รา เนื้อดำ กลิ่นเหม็น','เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 2–4 สัปดาห์','Store in a cool, dry, ventilated spot; do not refrigerate; use within 2–4 weeks',0,0,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (28,'หอมแดง','Shallot',5,21,80.00,NULL,NULL,NULL,NULL,NULL,NULL,'เปลือกแห้งสีน้ำตาลแดง เนื้อแน่น ไม่งอก ไม่เหลือง','งอกยาว เปลือกเน่าดำ รา เนื้อเละ','เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 3–4 สัปดาห์','Store in a cool, dry, ventilated spot; do not refrigerate; use within 3–4 weeks',0,0,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (29,'กระเทียม','Garlic',5,21,65.00,NULL,NULL,NULL,NULL,NULL,NULL,'เปลือกขาวหรือม่วงแห้งแน่น กลีบแน่นไม่งอก ไม่มีรา','งอกยาว เปลือกเน่าดำ รา เนื้อกลีบเละ กลิ่นเปรี้ยว','เก็บที่เย็นแห้งอากาศถ่ายเท ไม่แช่เย็น ใช้ภายใน 3–4 สัปดาห์','Store in a cool, dry, ventilated spot; do not refrigerate; use within 3–4 weeks',0,0,1,'approved',NULL,'2026-09-26 16:47:22');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (30,'มังคุด','Mangosteen',1,7,40.00,'W14023','มังคุด (ผิวกระ)',NULL,NULL,'auto',NULL,'เปลือกสีม่วงเข้มแน่น กลีบสีเขียวสด ไม่มียางเหลืองไหล','เปลือกแข็งแน่น ยางเหลืองไหล เนื้อดำน้ำตาล รา','เก็บที่เย็น 10–13°C ห่อด้วยกระดาษ ใช้ภายใน 1 สัปดาห์','Store at 10–13°C wrapped in paper; use within 1 week',1,3,1,'approved',NULL,'2026-09-26 18:20:07');
INSERT INTO `crops` (`id`, `name_th`, `name_en`, `category_id`, `base_shelf_days`, `market_price_per_kg`, `dit_product_code`, `dit_product_name`, `dit_unit`, `dit_unit_to_kg`, `dit_match_source`, `dit_price_status`, `normal_features_th`, `defect_examples_th`, `storage_tip_th`, `storage_tip_en`, `fridge_ok`, `fridge_extra_days`, `parcel_allowed`, `status`, `created_by`, `created_at`) VALUES (31,'ลิ้นจี่','Lychee',1,5,70.00,'W14029','ลิ้นจี่ พันธุ์จักรพรรดิ์',NULL,NULL,'auto',NULL,'เปลือกสีแดงอมชมพูสด เนื้อใสหวาน เมล็ดเล็ก','เปลือกน้ำตาลดำ เนื้อเมือก กลิ่นหมัก','แช่เย็น 2–5°C ใส่ถุงผักสด ใช้ภายใน 3–5 วัน','Refrigerate at 2–5°C in a produce bag; use within 3–5 days',1,3,1,'approved',NULL,'2026-09-26 18:20:07');
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (91,1,3,0.750);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (92,1,4,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (93,1,5,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (94,1,6,0.800);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (95,1,10,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (96,1,11,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (97,1,12,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (98,1,1,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (99,6,3,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (100,6,4,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (101,6,5,0.600);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (102,6,6,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (103,6,7,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (104,6,11,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (105,6,12,1.400);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (106,6,1,1.400);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (107,6,2,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (108,8,6,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (109,8,7,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (110,8,8,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (111,8,9,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (112,8,1,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (113,8,2,1.400);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (114,8,3,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (115,8,4,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (116,8,5,1.150);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (117,9,4,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (118,9,5,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (119,9,6,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (120,9,7,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (121,9,8,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (122,9,11,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (123,9,12,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (124,9,1,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (125,9,2,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (126,9,3,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (127,7,8,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (128,7,9,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (129,7,10,0.750);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (130,7,11,0.750);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (131,7,12,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (132,7,3,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (133,7,4,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (134,7,5,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (135,7,6,1.150);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (136,12,7,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (137,12,8,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (138,12,9,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (139,12,10,0.750);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (140,12,11,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (141,12,1,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (142,12,2,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (143,12,3,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (144,12,4,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (145,30,3,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (146,30,4,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (147,30,5,0.600);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (148,30,6,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (149,30,7,0.850);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (150,30,11,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (151,30,12,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (152,30,1,1.400);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (153,30,2,1.300);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (154,31,3,0.800);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (155,31,4,0.650);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (156,31,5,0.600);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (157,31,6,0.700);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (158,31,10,1.250);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (159,31,11,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (160,31,12,1.400);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (161,31,1,1.350);
INSERT INTO `crop_season_factors` (`id`, `crop_id`, `month`, `factor`) VALUES (162,31,2,1.250);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (1,22,'2026-09-25',35.00,NULL,'moc_dit','W13012','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13012&from_date=2026-09-20&to_date=2026-09-27','2026-09-27 15:07:57',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (2,26,'2026-09-25',27.50,NULL,'moc_dit','W13028','บาท/ กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13028&from_date=2026-09-20&to_date=2026-09-27','2026-09-27 15:07:57',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (3,2,'2026-09-25',30.00,NULL,'moc_dit','W14009','บาท/หวี','https://dataapi.moc.go.th/gis-product-prices?product_id=W14009&from_date=2026-09-13&to_date=2026-09-27','2026-09-27 13:12:34',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (4,3,'2026-09-25',22.50,NULL,'moc_dit','W13010','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13010&from_date=2026-09-13&to_date=2026-09-27','2026-09-27 13:12:34',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (5,4,'2026-09-25',22.50,NULL,'moc_dit','W13002','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13002&from_date=2026-09-13&to_date=2026-09-27','2026-09-27 13:12:34',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (6,20,'2026-09-25',12.00,NULL,'moc_dit','W13006','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13006&from_date=2026-08-28&to_date=2026-09-27','2026-09-27 15:07:48',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (7,18,'2026-09-25',50.00,NULL,'moc_dit','W13021','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13021&from_date=2026-08-28&to_date=2026-09-27','2026-09-27 15:07:48',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (8,17,'2026-09-25',17.50,NULL,'moc_dit','W13013','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13013&from_date=2026-08-28&to_date=2026-09-27','2026-09-27 15:07:48',0,NULL,NULL);
INSERT INTO `crop_reference_prices` (`id`, `crop_id`, `date`, `wholesale_price`, `retail_price`, `source`, `product_code`, `unit`, `source_url`, `fetched_at`, `rejected_as_outlier`, `outlier_baseline`, `outlier_ratio`) VALUES (9,21,'2026-09-25',42.50,NULL,'moc_dit','W13017','บาท/กก.','https://dataapi.moc.go.th/gis-product-prices?product_id=W13017&from_date=2026-08-28&to_date=2026-09-27','2026-09-27 15:07:48',1,10.00,4.2500);

SET FOREIGN_KEY_CHECKS = 1;
